-- =============================================================================
-- Switch from Shopify to YouCan, preserving all existing rows.
--
-- The autogenerated `prisma migrate diff` for this change is DROP+ADD, which
-- would lose merchant credentials and order history and would fail the new
-- NOT NULL constraints on any non-empty table. This file uses RENAME COLUMN
-- so the data carries over without a table rewrite (PostgreSQL renames are
-- metadata-only operations: O(1), no AccessExclusiveLock-blocking scan).
--
-- Rollout:
--   - Existing production database (already on the Shopify schema):
--       npx prisma migrate resolve --applied 20260101000000_init
--       npx prisma migrate deploy
--   - Green-field install:
--       npx prisma migrate deploy
--
-- Pre-checks before running in production:
--   1. Application code on this commit is shipped to every replica BEFORE
--      this migration is applied. The new code references the new column
--      names; running it against the old schema will 500.
--      → Cleanest path: scale workers to 0, migrate, redeploy, scale back up.
--   2. The rename is a column-name change only — column data (access tokens,
--      domains, order ids, raw payloads) carries over byte-for-byte. The
--      values themselves are still Shopify-style. YouCan-style values will
--      only start appearing for *new* installs after this deploys. Plan an
--      explicit re-install for any merchant you actually want migrated.
-- =============================================================================

-- ---- Merchant -------------------------------------------------------------

ALTER TABLE "Merchant" RENAME COLUMN "shopifyDomain"        TO "youcanStoreSlug";
ALTER TABLE "Merchant" RENAME COLUMN "shopifyAccessToken"   TO "youcanAccessToken";
ALTER TABLE "Merchant" RENAME COLUMN "shopifyWebhookSecret" TO "youcanWebhookSecret";

-- Rename the indexes to match the column rename. ALTER INDEX RENAME is
-- metadata-only — no rebuild, no AccessExclusiveLock blocking traffic.
ALTER INDEX "Merchant_shopifyDomain_key" RENAME TO "Merchant_youcanStoreSlug_key";
ALTER INDEX "Merchant_shopifyDomain_idx" RENAME TO "Merchant_youcanStoreSlug_idx";

-- YouCan returns a refresh token on the OAuth handshake; Shopify did not.
-- Nullable so existing rows don't need a backfill.
ALTER TABLE "Merchant" ADD COLUMN "youcanRefreshToken" TEXT;

-- Default country flips DZ → MA (YouCan's primary market). Affects only new
-- inserts; existing merchants keep whatever value they already had.
ALTER TABLE "Merchant" ALTER COLUMN "defaultCountryCode" SET DEFAULT 'MA';

-- ---- Order ----------------------------------------------------------------

ALTER TABLE "Order" RENAME COLUMN "shopifyOrderId"    TO "youcanOrderId";
ALTER TABLE "Order" RENAME COLUMN "shopifyOrderName"  TO "youcanOrderRef";
ALTER TABLE "Order" RENAME COLUMN "shopifyUpdatedAt"  TO "youcanUpdatedAt";
ALTER TABLE "Order" RENAME COLUMN "rawShopifyPayload" TO "rawYoucanPayload";

ALTER INDEX "Order_merchantId_shopifyOrderId_key"
  RENAME TO "Order_merchantId_youcanOrderId_key";
